version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sirca_api
    ports:
      - "8000:8000"
    environment:
      DOCKER: "true"
    env_file:
      - .env
    volumes:
      - .:/app
      - ./app/core/resources/templates:/app/app/core/resources/templates
      - ./app/core/resources/static:/app/app/core/resources/static
      - ./app/core/resources/media:/app/app/core/resources/media
      - ./sirca.db:/app/sirca.db
    depends_on:
      - redis
      - postgres
    restart: always

  redis:
    image: redis:7
    container_name: sirca_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

postgres:
    image: postgres:15
    container_name: sirca_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sirca_db
      POSTGRES_USER: sirca_user
      POSTGRES_PASSWORD: sirca_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
