# Generated by Django 5.1.5 on 2025-02-07 04:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_activation_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='activation_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
