# Generated by Django 5.1.5 on 2025-02-08 04:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_contador_reenvios_usuario_token_expiracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='activation_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
