# Generated by Django 5.1.5 on 2025-02-09 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuario_activation_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='email_sent_count',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='last_email_sent',
        ),
    ]
